#!/bin/bash

echo "Testing cd commands that might cause abort..."

# Test cases from the user's list
test_commands=(
    "pwd"
    "cd"
    "pwd"
    "cd .."
    "pwd"
    "cd .."
    "cd \$OLDPWD"
    "pwd"
    "cd ."
    "pwd"
    "pwd"
    'cd "."'
    "pwd"
    "pwd"
    "cd /Users"
    "pwd"
    "pwd"
    "cd ////"
    "pwd"
    "pwd"
    "cd ./././"
    "pwd"
    "pwd"
    "cd /"
    "pwd"
    "pwd"
    "cd '/////' "
    "pwd"
    "pwd"
    'cd "$PWD/file_tests"'
    "pwd"
    "cd '/////' 2>/dev/null"
    "cd '/etc'"
    "cd '/var'"
    'cd "doesntexist" 2>/dev/null'
    "cd ../../.."
    'cd "wtf" 2>/dev/null'
    "cd ?"
    "cd +"
    "cd _"
    "cd woof"
    "cd bark bark"
    "cd '/'"
    "pwd"
    'cd "doesntexist"'
    "pwd"
    "pwd"
    'cd "doesntexist"'
    "pwd"
    "pwd"
    "cd ../../.."
    "pwd"
    "pwd"
    'cd "wtf"'
    "pwd"
    "pwd"
    "cd .."
    "cd .."
    "pwd"
    "pwd"
    "cd ?"
    "pwd"
    "pwd"
    "cd +"
    "pwd"
    "pwd"
    "cd _"
    "pwd"
    "cd ../../"
    "cd -"
    "cd -"
    "pwd"
    "cd echo"
    "pwd"
    "pwd"
    "cd echo echo"
    "pwd"
    "pwd"
    "cd '/'"
    "pwd"
    "pwd"
    'cd $PWD/file_tests'
    "pwd"
    "pwd"
    'cd $OLDPWD/something'
    "pwd"
    "pwd"
    "cd ~"
    "cd - ananas dot jpeg"
    "pwd"
    "pwd"
    "cd includes/ djhwbdhwbd wgdyuhgw jdwjdh wuiydjwh"
    "pwd"
    "pwd"
    "cd ~ asd w dd q asd"
    "pwd"
    "pwd"
    "cd ~"
    "cd -"
    "pwd"
    "pwd"
    "cd -"
    "pwd"
    "pwd"
    "cd ~"
    "pwd"
    "pwd"
    "cd ../libft"
    "pwd"
    "pwd"
    "cd ../libft ojid iowjiojwoid joijd owjoid jwojd"
    "pwd"
    "exit"
)

# Run each command and check for issues
for cmd in "${test_commands[@]}"; do
    echo "Testing: $cmd"
    echo "$cmd" | timeout 5 ./minishell 2>&1 | head -10
    if [ $? -eq 134 ]; then
        echo "ABORT detected with command: $cmd"
        break
    fi
    sleep 0.1
done
